language: java
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - os: osx
      osx_image: xcode8

# actual code is inside lacuna/lacuna
before_install: cd lacuna

# verify runs both unit and integration tests
script: mvn clean && mvn verify -B

sudo: false

cache:
  directories:
  - $HOME/.m2
